// AUTO-GENERATED FILE.
// This file is auto-generated by the Ballerina OpenAPI tool.

import ballerina/http;

listener http:Listener ep0 = new (9090, config = {host: "localhost"});


service / on ep0 {
    # List all books
    #
    # + return - A list of books. 
    resource function get books() returns Book[] {
        return books.toArray();
    }
}
